### ISSUE TITLE
Planning: April 2018 meetup

### ISSUE THREAD

**Issue by danc86** [BrisPy/brispy-admin#10]
# Brisbane Python User Group meetup checklist

- [x] choose day (default: second Wednesday of the month)
- [x] choose venue (current default: Red Hat level 3)
- [ ] choose topics/find speakers (see the talks repo for ideas)
- [ ] announce on MeetUp (requires organiser access to the MeetUp group)
 - please use a suffix of "BrisPy: " for all meetups
- [ ] arrange food sponsorship (current default: Bloomberg - @nathan-hoad or @kaiw as point of contact)
- [ ] preorder food (see current default pizza order below)
- [ ] check waitlist numbers the week of the meetup and post MeetUp comment to remind folks to adjust their RSVP if they can't make it
- [ ] post MeetUp comment to thank attendees, speakers & sponsors and provide a pointing to the talks repo to both request and offer talks
- [ ] file the admin issue for the next month's MeetUp

## Meetup announcement notes:

- usual start time when hosting in the CBD is 5:30 PM for a 5:45 PM start. Add 15 minutes if hosting outside the CBD (e.g. at the State Library)
- mention the day & date in the meeting title (MeetUp's UI doesn't make it very prominent otherwise)
- thank both the venue sponsor and the food sponsor

## Speaker organisation notes:

- use the talks repo, that's what it's for :)
- the PyCon Australia schedule can also be a good resource for finding folks that are local to Brisbane and willing to talk about Python in public
- we aim for talks to run for 25-30 minutes, including time for questions (not coincidentally, this is also a typical PyCon AU timeslot)
- make sure speakers know which of them is speaking first
- make sure speakers have a mobile contact number for at least one of the organisers

## Meetup notes:

- explain the general plan for the evening (first talk, food, second talk)
- cover venue logistics in initial introduction (bathroom locations, fire exits)
- if the venue has guest wi-fi, make sure you know the password

Default food order is 15 Dominos pizzas for delivery at 6:15 pm:

- 3x Supreme
- 2x Chicken and Feta
- 2x Chili Pork
- 2x Lamb Tzatziki
- 2x Loaded Meatlovers
- 2x Vegorama
- 1x Supreme on gluten free base
- 1x Vegorama on gluten free base

**Comment by danc86** [comment]
Second Wednesday of the month will make this one 11 April. The usual venue on level 3 at Red Hat is free then. I am able to host.

As usual, our biggest challenge will be finding speakers :-)

**Comment by danc86** [comment]
Our second biggest challenge will be getting food sponsorship, since the offer from Bloomberg is no longer on the table.

**Comment by kaiw** [comment]
Looking at the abortive December attempt, we suggested a beginner's night plus "hacks". If organising a talk doesn't happen, we could do that?

**Comment by danc86** [comment]
My memory is imperfect but what I wrote down here: https://github.com/BrisPy/talks/issues/5#issuecomment-342790234 seems to suggest we were thinking of a talk in the first half, plus "hack night" in the second half, where the hack night also offers intro material and mentors for people who want to try running through it.

I think our idea was to make it a very casual, unstructured version of the beginner's night, while we experiment with the format. And we thought that keeping one normal talk for the first half caters for people who would normally come along who are not beginners and also don't want to *just* do unstructured hacking.

**Comment by nhoad** [comment]
Bloomberg will have to be taken off of the sponsor list, I'm afraid - the Brisbane office has been shut down.

**Comment by ncoghlan** [comment]
This one ain't a happening - see #11 for a possible restart of the group in 2019
