### ISSUE TITLE
Re-start the group

### ISSUE THREAD

**Issue by kaiw** [BrisPy/brispy-admin#11]
So this group has been dormant for quite a while now, but we've got a few people at Cyberhound/Superloop who are interested in starting it back up.

We have *tentative* food sponsorship & organisation from Superloop. I don't know whether we can use the offices here for a venue or whether we'd be looking elsewhere. We also have a tentative volunteer for talk organising, although having more than one person trying to herd cats is always useful.

I though I'd open an issue to see who in this org is still interested in being involved and what they (or their employer) can provide.

**Comment by danc86** [comment]
Thanks for kicking this off @kaiw, it's great to see renewed interest. I'm afraid in the short term I won't have any spare time to help out. Also just wanted to point out, in case you hadn't already heard the news, there is nobody left at Red Hat Brisbane to host this or help with sponsorship.

**Comment by EdJoJob** [comment]
I would love to help, but I also will not have much time to help in.

**Comment by kaiw** [comment]
As a quick update on this, we have confirmed food sponsorship and a venue (the Superloop city office at 333 Ann St). We're looking at trying to restart in January or February, to give some time to get things going.

Really what we need at this point is speakers, so any suggestions here would be extremely welcome.

**Comment by ncoghlan** [comment]
I asked Betsy Alpert from https://www.qut.edu.au/institute-for-future-environments/facilities/digital-observatory if she or Sam Hames might be interested in presenting something, and she said that could definitely work.

**Comment by kaiw** [comment]
Alright. I've opened #12 in the hopes that we can get something sorted by February, so I'll close this one.

I'm still trying to get a hold of people on this side who said they'd be involved, so I'll probably be inviting some new faces to this group in the future.

@ncoghlan That sounds awesome to me. If there's any chance they'd be available for February, that would be... very good. If I/we only have to find one speaker then that's probably do-able, even if I end up talking about some dumb project just to fill the slot and get things rolling.
