### ISSUE TITLE
Planning: February 2019 meetup

### ISSUE THREAD

**Issue by kaiw** [BrisPy/brispy-admin#12]
# Brisbane Python User Group meetup checklist

- [x] choose day: February 13th (second Wednesday of the month)
- [ ] choose venue (current default: Superloop, 333 Ann St)
- [ ] choose topics/find speakers (see the talks repo for ideas)
- [ ] announce on MeetUp (requires organiser access to the MeetUp group)
 - please use a suffix of "BrisPy: " for all meetups
- [ ] arrange food sponsorship (current default: Superloop)
- [ ] preorder food (see current default pizza order below)
- [ ] check waitlist numbers the week of the meetup and post MeetUp comment to remind folks to adjust their RSVP if they can't make it
- [ ] post MeetUp comment to thank attendees, speakers & sponsors and provide a pointing to the talks repo to both request and offer talks
- [ ] file the admin issue for the next month's MeetUp

## Meetup announcement notes:

- usual start time when hosting in the CBD is 5:30 PM for a 5:45 PM start. Add 15 minutes if hosting outside the CBD (e.g. at the State Library)
- mention the day & date in the meeting title (MeetUp's UI doesn't make it very prominent otherwise)
- thank both the venue sponsor and the food sponsor

## Speaker organisation notes:

- use the talks repo, that's what it's for :)
- the PyCon Australia schedule can also be a good resource for finding folks that are local to Brisbane and willing to talk about Python in public
- we aim for talks to run for 25-30 minutes, including time for questions (not coincidentally, this is also a typical PyCon AU timeslot)
- make sure speakers know which of them is speaking first
- make sure speakers have a mobile contact number for at least one of the organisers

## Meetup notes:

- explain the general plan for the evening (first talk, food, second talk)
- cover venue logistics in initial introduction (bathroom locations, fire exits)
- if the venue has guest wi-fi, make sure you know the password

Default food order is 15 Dominos pizzas for delivery at 6:15 pm:

- 3x Supreme
- 2x Chicken & Camembert
- 2x Godfather
- 2x BBQ Meatlovers
- 2x Vegorama
- 1x Pepperoni
- 1x Spicy Veg Trio
- 1x Supreme on gluten free base
- 1x Vegorama on gluten free base

**Comment by wrongontheinternet** [comment]
@ncoghlan You said that you had contact with Betsy Alpert from QUT's digital observatory, is she (or Sam) available to present on the 13th of February? I'm happy to chase that up if you'd like.

Do we have other ideas for talks? Or perhaps a better question: do people think we need to have the 2nd talk locked in before we send an advertisement to the Meetup group (which I'd like to do no later than Wednesday 23rd).

**Comment by ncoghlan** [comment]
I've pinged Betsy and pointed her at this thread. (I've also edited the issue to mention the intended date, as I almost missed it in the second comment)

**Comment by wrongontheinternet** [comment]
Thank you all who were involved!

Comments received were:
Needed more vegetarian pizzas
Request for a cheese only pizza

Pizza is messy. Having plates and napkins on a different table from the pizza is helpful for providing for peoples needs, but not for ensuring that the floor of the room is clean.
