### ISSUE TITLE
Join forces with the other Brisbane Python meetup group?

### ISSUE THREAD

**Issue by danc86** [BrisPy/brispy-admin#13]
I discovered by coincidence that Ryan Stuart has started a new Meetup group for Python users in Brisbane:

https://www.meetup.com/Brisbane-Python-Meetup/

They have got a meetup tentatively scheduled for March.

I don't think Ryan has been @-mentioned on any of these Github issues so maybe he didn't know this Github org existed or that people were discussing a meetup in February. I'm guessing that he saw the radio silence on the existing Meetup group at the end of last year, and took that to mean that everyone else had given up on it.

Does anyone have contact info for Ryan so we can figure out how to consolidate the two groups? I don't think it makes sense to keep running two separately for no reason.

**Comment by danc86** [comment]
@kaiw you might know the best way to get in touch with Ryan or Caleb?

**Comment by kaiw** [comment]
I've just messaged Caleb on an old email address I had from... somewhere... so fingers crossed. I absolutely agree that we don't need two Python meetups.

I can't speak for Jake, but I strongly suspect that neither of us really *want* to organise, and only did what we have because we thought no one else was (and also, I've done nothing... Jake has done all the work).

**Comment by cjrh** [comment]
@kaiw I got the mail. We thought the old meetup was dead :)  

@rstuart85 initiated the new meetup, he can discuss further options moving forward.

**Comment by rstuart85** [comment]
Hi everyone. The creation of the new Meetup was a completely innocent action. I was unaware that this was still going. Apologies for that.

I've got no motive here other than to ensure there is a functional and prosperous Python Meetup in Brisbane. To that end, I can offer support, in terms of both logistics and funding.

Happy to proceed in whatever way is most beneficial for the community.

**Comment by kaiw** [comment]
> The creation of the new Meetup was a completely innocent action. I was unaware that this was still going.

It wasn't! and yeah I'm sure no one here was assuming malice.

So next Wednesday is our first attempt at running again, and we have no idea what we're doing!

We've got venue and food sponsorship from Superloop, so for now I think we're good in that regard. The main pain point is going to be finding speakers, so any help there would be much appreciated.

After Wednesday we'll also have a better idea of how the new venue is going to work out. If anyone here is going to make it to the meetup on Wednesday, we could discuss options there.

**Comment by rstuart85** [comment]
>we have no idea what we're doing

To be honest, I don't either strictly speaking, but we have some ideas that I'd be happy to share.

>The main pain point is going to be finding speakers, so any help there would be much appreciated.

Have ideas here as well. Again, happy to share. Is the correct medium this issue?

>we'll also have a better idea of how the new venue is going to work out

On the venue front, RCL is a good option. It's set up for events, host a lot of meetups, and is owned by the Australian Computer Society. I think it would be worth considering.

>If anyone here is going to make it to the meetup on Wednesday, we could discuss options there.

I couldn't make it, unfortunately.

**Comment by kaiw** [comment]
> Have ideas here as well. Again, happy to share. Is the correct medium this issue?

I'm happy to have discussions here, but also in-person _can_ be better for organising. If you'd like to sit down for 20 minutes and try to make some plans, I'd be happy to meet up anywhere Valley-adjacent in the next weeks (which of course goes for anyone else here who's interested as well).

> On the venue front, RCL is a good option. It's set up for events, host a lot of meetups, and is owned by the Australian Computer Society. I think it would be worth considering.

So the venue from Wednesday (Superloop Brisbane office) was pretty good, with the main issue being the usual security getting-people-in-to-the-building problem. Personally, I'd be somewhat interested in moving to RCL, but business may have other considerations.

**Comment by rstuart85** [comment]
>If you'd like to sit down for 20 minutes and try to make some plans, I'd be happy to meet up anywhere Valley-adjacent in the next weeks

Yea, of course, I think that's a great idea. You can email me using ryan -AT- kapiche.com

>So the venue from Wednesday (Superloop Brisbane office) was pretty good, with the main issue being the usual security getting-people-in-to-the-building problem. Personally, I'd be somewhat interested in moving to RCL, but business may have other considerations.

I got some separate feedback from attendees I know that they thought the venue was too small. Do you want to check with the business whether there is an issue moving the event to RCL? Maybe they could send a banner to put up at the events?

**Comment by cjrh** [comment]
The format we were considering for the new python meetup was the following:

- One meetup per month
- Two speakers each meetup; one talk focused on beginner/intro topics, and one focused on general (can be beginner or intermediate or expert)
- 6-8pm (or even 6-7:30pm. Ending a bit earlier will make it more attractive for people who have kids, for example).
- no supply food or drink. Supplying these tends to influence the distribution of kinds of people who show up to meetups.

What are these kinds of considerations for the superloop-driven meetup?

**Comment by kaiw** [comment]
>  * One meetup per month
> 
>  * Two speakers each meetup; one talk focused on beginner/intro topics, and one focused on general (can be beginner or intermediate or expert)
>
>  * 6-8pm (or even 6-7:30pm. Ending a bit earlier will make it more attractive for people who have kids, for example).

This all sounds good to us, although I think that historically we haven't had enough speakers that we were able to be picky with topics... I'd be extremely happy to be wrong here though.

>  * no supply food or drink. Supplying these tends to influence the distribution of kinds of people who show up to meetups.

I could go either way here. I don't think I really understand the concern, but maybe that's because I don't have enough context.

> What are these kinds of considerations for the superloop-driven meetup?

As it turns out, business is fine with a venue move!

**Comment by kaiw** [comment]
Just for the record here...

We're planning on moving to RCL, and are reconsidering what we'll do about food. We're going to try to keep the usual second-Wednesday-of-the-month cadence, venue pending.

As soon as we have a venue booking, I'll open a new issue for the March meetup, which will [_crosses fingers_]  be on March 13.
