### ISSUE TITLE
Planning: March '19 meetup

### ISSUE THREAD

**Issue by rstuart85** [BrisPy/brispy-admin#14]
# Brisbane Python User Group meetup checklist

- [x] choose day: **Wednesday, March 13th**
- [x] choose venue: **River City Labs, capacity of 75** (awaiting confirmation)
- [x] choose topics/find speakers (*preliminary*)
 - **Beginner:** Intro to flake8 and black for improving code quality.
 - **General:** What is Cython and when is a good time to use it?
- [x] announce on MeetUp (requires organiser access to the MeetUp group)
 - please use a suffix of "BrisPy: " for all meetups
- [x] arrange food sponsorship (current default: Superloop)
- [ ] preorder food: *Venue has suggesting using [Art of Catering](https://artofcatering.com.au/) for finger food.*
- [ ] check waitlist numbers the week of the meetup and post MeetUp comment to remind folks to adjust their RSVP if they can't make it
- [ ] post MeetUp comment to thank attendees, speakers & sponsors and provide a pointing to the talks repo to both request and offer talks
- [ ] file the admin issue for the next month's MeetUp

## Meetup announcement notes:

- Meet at 5:45pm for a 6pm start. The venue is [here](https://www.google.com/maps/place/River+City+Labs/@-27.4567595,153.0342452,15z/data=!4m2!3m1!1s0x0:0xc834513bb0e3cc85?ved=2ahUKEwiEvqClz-LgAhXDAnIKHYRuCx4Q_BIwFXoECAMQCA).  Schedule:
-- **6:00**: Welcome, sponsors, call for speakers.
-- **6:05**: Beginner track.
-- **6:35**: Break for toilet and networking.
-- **6:45**: General track.
-- **7:15**: Networking.
- mention the day & date in the meeting title (MeetUp's UI doesn't make it very prominent otherwise)
- thank both the venue sponsor and the food sponsor

## Speaker organisation notes:

- use the talks repo, that's what it's for :)
- the PyCon Australia schedule can also be a good resource for finding folks that are local to Brisbane and willing to talk about Python in public
- we aim for talks to run for 25-30 minutes, including time for questions (not coincidentally, this is also a typical PyCon AU timeslot)
- make sure speakers know which of them is speaking first
- make sure speakers have a mobile contact number for at least one of the organisers

## Meetup notes:

- explain the general plan for the evening (first talk, food, second talk)
- cover venue logistics in initial introduction (bathroom locations, fire exits)
- if the venue has guest wi-fi, make sure you know the password

**Comment by cjrh** [comment]
Event happened, and was successful.
