### ISSUE TITLE
Planning: 10 April 2019

### ISSUE THREAD

**Issue by cjrh** [BrisPy/brispy-admin#15]
# Brisbane Python User Group meetup checklist

- [x] choose day (default: second Wednesday of the month)
- [x] choose venue (current default: Superloop, 333 Ann St)
- [x] choose topics/find speakers (see the talks repo for ideas)
  - Kieran Thompson: Dates and Times in Python
  - Ashwini Balnaves: Pytest
- [x] announce on MeetUp (requires organiser access to the MeetUp group)
 - please use a suffix of "BrisPy: " for all meetups
- [x] arrange food sponsorship (current default: Superloop)
- [x] preorder food (see current default pizza order below)
- [x] check waitlist numbers the week of the meetup and post MeetUp comment to remind folks to adjust their RSVP if they can't make it
- [ ] post MeetUp comment to thank attendees, speakers & sponsors and provide a pointing to the talks repo to both request and offer talks
- [ ] file the admin issue for the next month's MeetUp

## Meetup announcement notes:

- usual start time when hosting in the CBD is 5:30 PM for a 5:45 PM start. Add 15 minutes if hosting outside the CBD (e.g. at the State Library)
- mention the day & date in the meeting title (MeetUp's UI doesn't make it very prominent otherwise)
- thank both the venue sponsor and the food sponsor

## Speaker organisation notes:

- use the talks repo, that's what it's for :)
- the PyCon Australia schedule can also be a good resource for finding folks that are local to Brisbane and willing to talk about Python in public
- we aim for talks to run for 25-30 minutes, including time for questions (not coincidentally, this is also a typical PyCon AU timeslot)
- make sure speakers know which of them is speaking first
- make sure speakers have a mobile contact number for at least one of the organisers

## Meetup notes:

- explain the general plan for the evening (first talk, food, second talk)
- cover venue logistics in initial introduction (bathroom locations, fire exits)
- if the venue has guest wi-fi, make sure you know the password

Default food order is 15 Dominos pizzas for delivery at 6:15 pm:

- 3x Supreme
- 2x Chicken & Camembert
- 2x Godfather
- 2x BBQ Meatlovers
- 2x Vegorama
- 1x Pepperoni
- 1x Spicy Veg Trio
- 1x Supreme on gluten free base
- 1x Vegorama on gluten free base

**Comment by cjrh** [comment]
@kaiw @rstuart85 Speakers are booked for the next meetup (10 April). Would be good to do the next steps, set up the event on meetup.com, etc. I'll leave all those things in both your capable hands 👍

**Comment by kaiw** [comment]
Food platters have been ordered and are being delivered to you tomorrow afternoon.

**Comment by cjrh** [comment]
@kaiw That's 5pm right?  Also, @kaiw would you like to give the introductions and kickoff tomorrow?

**Comment by kaiw** [comment]
Yes, should be delivered at 5pm. I don't mind about the kickoff, but I'm either Jake or I can do this if you'd prefer.

**Comment by cjrh** [comment]
Sure, we can figure it out tomorrow. I would perhaps like a few minutes to encourage people to upvote talk topics and to volunteer to give some of those talks.
