### ISSUE TITLE
Planning: August meetup

### ISSUE THREAD

**Issue by ncoghlan** [BrisPy/brispy-admin#5]
# Brisbane Python User Group meetup checklist

- [x] choose day: Wednesday, August 9th (post-conference)
- [x] choose venue (Red Hat level 3)
- [x] choose topics/find speakers (see the talks repo for ideas)
  - @ncoghlan: [Frontend integration testing with splinter](https://2017.pycon-au.org/schedule/presentation/42/)
  - @Charcol: [Improving your documentation](https://2017.pycon-au.org/schedule/presentation/10/)
- [x] announce on MeetUp (requires organiser access to the MeetUp group)
- [x] arrange food sponsorship (current default: Microsoft Azure Development Team - Azadeh Khojandi is our point of contact)
- [x] preorder food (see current default pizza order below)
- [x] check waitlist numbers the week of the meetup and post MeetUp comment to remind folks to adjust their RSVP if they can't make it
- [ ] post MeetUp comment to thank attendees, speakers & sponsors and provide a pointing to the talks repo to both request and offer talks
- [x] file the admin issue for the next month's MeetUp

## Meetup announcement notes:

- usual start time when hosting in the CBD is 5:30 PM for a 5:45 PM start. Add 15 minutes if hosting outside the CBD (e.g. at the State Library)
- mention the day & date in the meeting title (MeetUp's UI doesn't make it very prominent otherwise)
- thank both the venue sponsor and the food sponsor

## Speaker organisation notes:

- use the talks repo, that's what it's for :)
- the PyCon Australia schedule can also be a good resource for finding folks that are local to Brisbane and willing to talk about Python in public
- we aim for talks to run for 25-30 minutes, including time for questions (not coincidentally, this is also a typical PyCon AU timeslot)
- make sure speakers know which of them is speaking first
- make sure speakers have a mobile contact number for at least one of the organisers

## Meetup notes:

- explain the general plan for the evening (first talk, food, second talk)
- cover venue logistics in initial introduction (bathroom locations, fire exits)
- if the venue has guest wi-fi, make sure you know the password

Default food order is 15 Dominos pizzas for delivery at 6:15 pm:

- 3x Supreme
- 2x Chicken and Feta
- 2x Chili Pork
- 2x Lamb Tzatziki
- 2x Loaded Meatlovers
- 2x Vegorama
- 1x Supreme on gluten free base
- 1x Vegorama on gluten free base

**Comment by ncoghlan** [comment]
Second speaker notes:
- Charelle will have already left for Melbourne by then (as conference venue setup starts on the 2nd)
- Clinton will have already left for Melbourne
- Anna Gerber has other commitments (but will be happy to speak in September)
- Fraser Tweedale may have been able to make time, but it wouldn't have been straightforward

**Comment by ncoghlan** [comment]
I just noticed that I'm technically double-booked for the 2nd as well. While the other event is one I can skip easily enough, I'm wondering if it may make more sense to move this to the 9th and have it be a *post* conference meetup instead of a preview.

I'll check with Charelle to see if the 9th will work for her, and if so, I'll go back to the original plan (my splinter talk and her documentation one), just on a different night :)

**Comment by ncoghlan** [comment]
Delaying the meetup a week completely solves the speaker scheduling problem, so I've revised the plan accordingly :)

**Comment by ncoghlan** [comment]
Meetup announcement has been drafted, but I'll contact Azadeh about catering before hitting publish.

**Comment by danc86** [comment]
As far as food goes... I don't think that the MSFT offer was ongoing, although we can wait and see if there is any response there (I might have misunderstood).

Meanwhile budget from RHT has been approved for one more meetup. We just need to figure out whether to use one or the other, at least a day or two prior to the meetup so that we can get it ordered. I was thinking Danny Boys sandwiches this time for some variety (bored of pizza).

**Comment by danc86** [comment]
... regardless, I think we should go ahead and announce the meetup ASAP and just omit mention of food for now, until we have got that figured out.

**Comment by ncoghlan** [comment]
Sounds like a plan. Published: https://www.meetup.com/Brisbane-Python-User-Group/events/241714742/!

**Comment by kaiw** [comment]
I've talked with Trent about getting Bloomberg to sponsor food, and we can probably make this happen. If that's acceptable, we can probably work out details (budget etc.) at the next meeting, or pycon-au or whatever.

**Comment by danc86** [comment]
@kaiw what's the verdict on Bloomberg food sponsorship? We will need to get our order in ASAP if Red Hat is going to provide food this month.

**Comment by danc86** [comment]
@kaiw btw slightly related... do you know who controls the "Netbox Blue" user account on Meetup.com? Is it perhaps Trent? It would be good to get that account taken out of the list of organisers, now that Netbox Blue is not a thing anymore.

**Comment by kaiw** [comment]
@danc86 Sorry, I was waiting for a response before moving ahead. Bloomberg is happy to sponsor food for future meetups, though if you've got Red Hat budget for this month then that would let us figure out budget for next month.

As for the Netbox Blue user, yes it's Trent. We *could* remove them as an admin, but he's currently paying for this meetup group. I think the plan is to migrate this to be Bloomberg owned a some stage, but again we could discuss.

**Comment by anchat1990** [comment]
@danc86 @ncoghlan @kaiw We have a budget of $300 from red hat approved for this month. 
[Danny boys](http://dannyboys.com.au/catering/) have some good options that arent pizza.

**Comment by ncoghlan** [comment]
Late amendment to the schedule: @Charcol isn't feeling well, so @clintonroy is going to present his State Machines talk instead: https://2017.pycon-au.org/schedule/presentation/33/

**Comment by ncoghlan** [comment]
I didn't do the thank you post in Meetup, but marking this as done regardless :)
