### ISSUE TITLE
 Planning: November meetup 

### ISSUE THREAD

**Issue by romanofski** [BrisPy/brispy-admin#8]
# Brisbane Python User Group meetup checklist

- [x] choose day (default: second Wednesday of the month)
- [x] choose venue (current default: Red Hat level 3)
- [x] choose topics/find speakers (see the talks repo for ideas)
- [x] announce on MeetUp (requires organiser access to the MeetUp group)
  - please use a prefix of "BrisPy: " for all meetups
- [ ] arrange food sponsorship (current default: None, although Red Hat, Bloomberg, and Microsoft are all potential candidates)
- [ ] preorder food (see current default pizza order below)
- [ ] check waitlist numbers the week of the meetup and post MeetUp comment to remind folks to adjust their RSVP if they can't make it
- [ ] post MeetUp comment to thank attendees, speakers & sponsors and provide a pointing to the talks repo to both request and offer talks
- [ ] file the admin issue for the next month's MeetUp

## Meetup announcement notes:

- usual start time when hosting in the CBD is 5:30 PM for a 5:45 PM start. Add 15 minutes if hosting outside the CBD (e.g. at the State Library)
- mention the day & date in the meeting title (MeetUp's UI doesn't make it very prominent otherwise)
- thank both the venue sponsor and the food sponsor

## Speaker organisation notes:

- use the talks repo, that's what it's for :)
- the PyCon Australia schedule can also be a good resource for finding folks that are local to Brisbane and willing to talk about Python in public
- we aim for talks to run for 25-30 minutes, including time for questions (not coincidentally, this is also a typical PyCon AU timeslot)
- make sure speakers know which of them is speaking first
- make sure speakers have a mobile contact number for at least one of the organisers

## Meetup notes:

- explain the general plan for the evening (first talk, food, second talk)
- cover venue logistics in initial introduction (bathroom locations, fire exits)
- if the venue has guest wi-fi, make sure you know the password

Default food order is 15 Dominos pizzas for delivery at 6:15 pm:

- 3x Supreme
- 2x Chicken and Feta
- 2x Chili Pork
- 2x Lamb Tzatziki
- 2x Loaded Meatlovers
- 2x Vegorama
- 1x Supreme on gluten free base
- 1x Vegorama on gluten free base

**Comment by danc86** [comment]
So... the October meetup is notionally on, in 5 days from now...

Are there any promising leads for presenters?

**Comment by danc86** [comment]
@ncoghlan you might have some ideas I hope :-)

**Comment by romanofski** [comment]
Maybe push it out to November ... since catering might also be an obstacle for such a short notice. Just sayin ...

**Comment by nhoad** [comment]
Hey, Nathan from Bloomberg here - late notice catering is fine, I just need to know the day :)

**Comment by ncoghlan** [comment]
Since the last two meet-ups were 2nd Wednesday, I meant to change the default in the template, but I forgot :)

Still shortish notice, but not *as* short as it could be.

I'd be happy to do a presentation on getting into the CPython code base: https://github.com/BrisPy/talks/issues/19

While it's a bit meta, perhaps it would be worth doing a "What goes into making a monthly meetup?" presentation, walking through why we're currently a bit hit-or-miss on actually getting things organised in a timely fashion each month?

And then for November, we could potentially look at the "Beginner's Night" idea from https://github.com/BrisPy/talks/issues/5 (@anchat1990 may have some suggestions on that front, having recently jumped from the JS world into a 10+ year old Python project spanning a couple of different generations of Python web tech)

**Comment by danc86** [comment]
I don't think we can really string out "what goes into organising the meetup" into a full 30 minute talk. It would be at most 5 minutes of me complaining, and then largely about Red Hat bureaucracy for obtaining food :-P

@ncoghlan giving BrisPy/talks#19 sounds like a good one.

For the second talk I pinged Sam on BrisPy/talks#6 on the off chance that he has a talk ready up his sleeve, or would be willing to whip one up.

I also like the idea of the beginniner's night but that one's worth not rushing into so I agree we should save it for November.

**Comment by danc86** [comment]
That's a negative from Sam (too short notice). @romanofski and I had a quick brainstorm and we couldn't come up with any other ideas of talks to whip up at short notice. So I think we will have to skip October and go for November instead.

**Comment by danc86** [comment]
Renamed the issue to be about November meetup, which will therefore be on 8 November.

We have a few options for talks now:

* BrisPy/talks#6 by @SamHames, he has said yes for November already
* BrisPy/talks#19 by @ncoghlan 
* BrisPy/talks#5 Beginners Night -- but we would need to discuss and decide on what exactly the format should be for this one
* any other ideas that other people are prepared to talk about

**Comment by danc86** [comment]
I've put up a placeholder event on Meetup.com for 8 November (but not announced yet). And booked the usual room on level 3.

**Comment by danc86** [comment]
Let's go with Caterpillar, and Getting into the Cpython code base, as the two talks for November, since there's still a bit of uncertainty about the format for the beginner's night. @ncoghlan  and @SamHames are you both still good to go? If so I will update the Meetup.com event and sound out the announcement for it.

**Comment by SamHames** [comment]
Yes, still good to go :)

**Comment by ncoghlan** [comment]
Sounds good to me! I think the beginner night could also be a good opportunity to take @elusivenode up on the offer of a larger venue in https://github.com/BrisPy/brispy-admin/issues/1#issuecomment-322115282

**Comment by ncoghlan** [comment]
Oops, that was unclear - I agree deferring the beginner night makes sense, and I think we'll probably want a larger venue for it. I'll file a new issue for that.

**Comment by danc86** [comment]
Okay! Meetup.com event is updated and meeting is announced.

@ncoghlan I just used the suggested title from #19 but please edit it if you want the title to be different.

@nathan-hoad is Bloomberg all set to supply pizza for us again for this meetup? Can I leave that in your hands?

**Comment by nhoad** [comment]
@danc86 Yep, all good from us!

**Comment by danc86** [comment]
@nathan-hoad btw if you can send me (or link me to) a suitable version of the Bloomberg logo, I can add it to the Meetup.com page as a sponsor.

**Comment by kaiw** [comment]
@danc86 We're... trying to figure out the logo/attribution/something situation. I'll update the page when we've got the okay from business. Thanks!
