### ISSUE TITLE
Planning: December meetup

### ISSUE THREAD

**Issue by ncoghlan** [BrisPy/brispy-admin#9]
I've cleared the usual checklist here, as in previous years the most we've ever done in December is to point folks at the Brisbane Tech Meetup drinks at the Platform Bar and say "This is happening if you're interested".

It's not clear if anything like that's going to be happening again this year, so I'm filing this now with the aim of having something to tell folks at the November meetup :)

**Comment by ncoghlan** [comment]
@danc86 also suggested that we could target December for a beginner's night: https://github.com/BrisPy/talks/issues/5#issuecomment-337069545

(Note: I'll be away from December 10th, but that's not necessarily a blocker for anything folks want to do)

**Comment by anchat1990** [comment]
Would it help to send out a survey to existing members (as well as members of Brisbane Tech Newbies) to see what people are interested in?
I could get in touch with Caitlin (the organiser of Brisbane Tech Newbies) who could help us with sending out an email?

**Comment by ncoghlan** [comment]
Seeking data before making decisions about things? That's far too logical and sensible an idea :)

But yeah, I think if you had some potential talk ideas lined up, then a member survey could be a good way to decide which ones to actually develop into presentations.

**Comment by danc86** [comment]
There seemed to be a fair bit of interest in having a December meeting on the usual date which would be 13 December.

Right now we are thinking a normal talk for the first half (perhaps BrisPy/talks#21 ?) and the "hack night" idea I described here for the second half:

https://github.com/BrisPy/talks/issues/5#issuecomment-342790234

**Comment by danc86** [comment]
So unfortunately we haven't succeeded in finding a talk for first half of the December meetup. Unless anything comes up in the very near future I think we will need to skip December.

However it would be good to announce the Brisbane tech xmas drinks event. @clintonroy do you happen to know who organises that, so we can ask them about promoting it to the BrisPy meetup?

**Comment by ncoghlan** [comment]
@danc86 If I'm able to convince the on-site interactive game designer for the Woodford Folk Festival to come speak about what they're doing with https://github.com/RealEngine/Real_Engine/, would you be happy to still organise a meetup for next week?

**Comment by danc86** [comment]
@ncoghlan the timing will be tight... but I am still free to host it on 13 Dec if we want to go ahead.

The other things I would want to double-check before we schedule it are:

@nathan-hoad is Bloomberg okay to supply catering again?

And do we have enough experienced Pythonistas attending as mentors for the second half? So far there would only be me, @romanofski @kaiw @samhames what about you guys? Anyone else?

**Comment by anchat1990** [comment]
I can help with the noobs...

**Comment by ncoghlan** [comment]
OK, I'll ask @Monley if he or one of the other contributors might be able to commit to giving a presentation.

**Comment by nhoad** [comment]
All good from Bloomberg for catering!

**Comment by kaiw** [comment]
I have to admit I'm not sure what the mentoring is likely to involve, but yeah I'm happy to help out!

**Comment by Monley** [comment]
I'll ask the team if someone is available to do a presentation.

**Comment by romanofski** [comment]
@danc86 I'm also happy to mentor.

**Comment by kaiw** [comment]
Given that the proposed date is two days away, should we just postpone this plan until January? I feel like even if we announced now, we probably wouldn't get great attendance, which would be particularly unfortunate for the beginner's night.

**Comment by Monley** [comment]
Hi,
Yes, apologies for not getting back sooner. I had one person keen to do a
presentation, but they are not back to Brisbane in time.
Thank you for your efforts to organise this.
If you think of anyone who might be keen and have time send them my way.
Hope to catch up one day to discuss the project as it grows.
Cheers,
Tim


-----------------------------
Playfulness Everywhere
http://timmonley.com/ <http://www.timmonley.com>
http://www.follygames.com/

**Comment by danc86** [comment]
Well, this well and truly fell through. Let's try a bit harder for our next one, which will be in April. :-)

See #10
